apiVersion: v1
kind: Service
metadata:
  name: customer-churn-service
  namespace: ml-prod
  labels:
    app: customer-churn-api
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: customer-churn-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000